### ISSUE TITLE
[Feature request] Accept os.PathLike

### ISSUE THREAD

**Issue by p0lm** [h2non/filetype.py#79] opened 2020-12-16 01:39 UTC
Currently filetype.guess does not accept PathLike objects (see https://docs.python.org/3/library/os.html#os.PathLike) as used by pathlib.Path. It would be nice if this was possible.

**Comment by dosas** [comment] 2020-12-20 20:31
Possible duplicate of https://github.com/h2non/filetype.py/issues/61

**Closed** 2020-12-22 00:42 UTC
